exports.fine_motor_medicines = [
    "SYR KRETSOMAG 10ML DAILY FOR 1 MONTH",
    "SYR QCARWIO 10ML DAILY FOR 1 MONTH",
    "T. KRANONQ10 1 TAB DAILY FOR  1MONTH",
    "T.MINAMINQPLUS 1 TAB DAILY FOR 1 MONTH",
    "T.BYCINE OD 1 TAB DAILY FOR 1 MONTH",
    "T.REJUNEX CDS 1 TAB DAILY FOR 1 MONTH"
] ;
